web:
  build: .
  volumes:
    - .:/app
  links:
    - db
  ports:
    - "3000"
db:
  image: postgres
  ports:
    - "5432:5432"
  environment:
    - POSTGRES_PASSWORD=postgres
    - POSTGRES_USER=postgres
